services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.4
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    command:
      - "start-dev"
